// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	CommandsChannelsCMDOverrides string
	CommandsChannelsOverrides    string
}{
	CommandsChannelsCMDOverrides: "commands_channels_cmd_overrides",
	CommandsChannelsOverrides:    "commands_channels_overrides",
}
