// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/strmangle"
	"github.com/volatiletech/sqlboiler/types"
)

// CommandsChannelsCMDOverride is an object representing the database table.
type CommandsChannelsCMDOverride struct {
	ID                  int64            `boil:"id" json:"id" toml:"id" yaml:"id"`
	ChannelsOverridesID int64            `boil:"channels_overrides_id" json:"channels_overrides_id" toml:"channels_overrides_id" yaml:"channels_overrides_id"`
	Enabled             bool             `boil:"enabled" json:"enabled" toml:"enabled" yaml:"enabled"`
	AutoDelete          bool             `boil:"auto_delete" json:"auto_delete" toml:"auto_delete" yaml:"auto_delete"`
	RequiredRoles       types.Int64Array `boil:"required_roles" json:"required_roles" toml:"required_roles" yaml:"required_roles"`

	R *commandsChannelsCMDOverrideR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L commandsChannelsCMDOverrideL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var CommandsChannelsCMDOverrideColumns = struct {
	ID                  string
	ChannelsOverridesID string
	Enabled             string
	AutoDelete          string
	RequiredRoles       string
}{
	ID:                  "id",
	ChannelsOverridesID: "channels_overrides_id",
	Enabled:             "enabled",
	AutoDelete:          "auto_delete",
	RequiredRoles:       "required_roles",
}

// commandsChannelsCMDOverrideR is where relationships are stored.
type commandsChannelsCMDOverrideR struct {
	ChannelsOverride *CommandsChannelsOverride
}

// commandsChannelsCMDOverrideL is where Load methods for each relationship are stored.
type commandsChannelsCMDOverrideL struct{}

var (
	commandsChannelsCMDOverrideColumns               = []string{"id", "channels_overrides_id", "enabled", "auto_delete", "required_roles"}
	commandsChannelsCMDOverrideColumnsWithoutDefault = []string{"channels_overrides_id", "enabled", "auto_delete", "required_roles"}
	commandsChannelsCMDOverrideColumnsWithDefault    = []string{"id"}
	commandsChannelsCMDOverridePrimaryKeyColumns     = []string{"id"}
)

type (
	// CommandsChannelsCMDOverrideSlice is an alias for a slice of pointers to CommandsChannelsCMDOverride.
	// This should generally be used opposed to []CommandsChannelsCMDOverride.
	CommandsChannelsCMDOverrideSlice []*CommandsChannelsCMDOverride

	commandsChannelsCMDOverrideQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	commandsChannelsCMDOverrideType                 = reflect.TypeOf(&CommandsChannelsCMDOverride{})
	commandsChannelsCMDOverrideMapping              = queries.MakeStructMapping(commandsChannelsCMDOverrideType)
	commandsChannelsCMDOverridePrimaryKeyMapping, _ = queries.BindMapping(commandsChannelsCMDOverrideType, commandsChannelsCMDOverrideMapping, commandsChannelsCMDOverridePrimaryKeyColumns)
	commandsChannelsCMDOverrideInsertCacheMut       sync.RWMutex
	commandsChannelsCMDOverrideInsertCache          = make(map[string]insertCache)
	commandsChannelsCMDOverrideUpdateCacheMut       sync.RWMutex
	commandsChannelsCMDOverrideUpdateCache          = make(map[string]updateCache)
	commandsChannelsCMDOverrideUpsertCacheMut       sync.RWMutex
	commandsChannelsCMDOverrideUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force bytes in case of primary key column that uses []byte (for relationship compares)
	_ = bytes.MinRead
)

// OneP returns a single commandsChannelsCMDOverride record from the query, and panics on error.
func (q commandsChannelsCMDOverrideQuery) OneP() *CommandsChannelsCMDOverride {
	o, err := q.One()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single commandsChannelsCMDOverride record from the query.
func (q commandsChannelsCMDOverrideQuery) One() (*CommandsChannelsCMDOverride, error) {
	o := &CommandsChannelsCMDOverride{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for commands_channels_cmd_overrides")
	}

	return o, nil
}

// AllP returns all CommandsChannelsCMDOverride records from the query, and panics on error.
func (q commandsChannelsCMDOverrideQuery) AllP() CommandsChannelsCMDOverrideSlice {
	o, err := q.All()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all CommandsChannelsCMDOverride records from the query.
func (q commandsChannelsCMDOverrideQuery) All() (CommandsChannelsCMDOverrideSlice, error) {
	var o []*CommandsChannelsCMDOverride

	err := q.Bind(&o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to CommandsChannelsCMDOverride slice")
	}

	return o, nil
}

// CountP returns the count of all CommandsChannelsCMDOverride records in the query, and panics on error.
func (q commandsChannelsCMDOverrideQuery) CountP() int64 {
	c, err := q.Count()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all CommandsChannelsCMDOverride records in the query.
func (q commandsChannelsCMDOverrideQuery) Count() (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count commands_channels_cmd_overrides rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table, and panics on error.
func (q commandsChannelsCMDOverrideQuery) ExistsP() bool {
	e, err := q.Exists()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q commandsChannelsCMDOverrideQuery) Exists() (bool, error) {
	var count int64

	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if commands_channels_cmd_overrides exists")
	}

	return count > 0, nil
}

// ChannelsOverrideG pointed to by the foreign key.
func (o *CommandsChannelsCMDOverride) ChannelsOverrideG(mods ...qm.QueryMod) commandsChannelsOverrideQuery {
	return o.ChannelsOverride(boil.GetDB(), mods...)
}

// ChannelsOverride pointed to by the foreign key.
func (o *CommandsChannelsCMDOverride) ChannelsOverride(exec boil.Executor, mods ...qm.QueryMod) commandsChannelsOverrideQuery {
	queryMods := []qm.QueryMod{
		qm.Where("id=?", o.ChannelsOverridesID),
	}

	queryMods = append(queryMods, mods...)

	query := CommandsChannelsOverrides(exec, queryMods...)
	queries.SetFrom(query.Query, "\"commands_channels_overrides\"")

	return query
} // LoadChannelsOverride allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (commandsChannelsCMDOverrideL) LoadChannelsOverride(e boil.Executor, singular bool, maybeCommandsChannelsCMDOverride interface{}) error {
	var slice []*CommandsChannelsCMDOverride
	var object *CommandsChannelsCMDOverride

	count := 1
	if singular {
		object = maybeCommandsChannelsCMDOverride.(*CommandsChannelsCMDOverride)
	} else {
		slice = *maybeCommandsChannelsCMDOverride.(*[]*CommandsChannelsCMDOverride)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &commandsChannelsCMDOverrideR{}
		}
		args[0] = object.ChannelsOverridesID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &commandsChannelsCMDOverrideR{}
			}
			args[i] = obj.ChannelsOverridesID
		}
	}

	query := fmt.Sprintf(
		"select * from \"commands_channels_overrides\" where \"id\" in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)

	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load CommandsChannelsOverride")
	}
	defer results.Close()

	var resultSlice []*CommandsChannelsOverride
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice CommandsChannelsOverride")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		object.R.ChannelsOverride = resultSlice[0]
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ChannelsOverridesID == foreign.ID {
				local.R.ChannelsOverride = foreign
				break
			}
		}
	}

	return nil
}

// SetChannelsOverrideG of the commands_channels_cmd_override to the related item.
// Sets o.R.ChannelsOverride to related.
// Adds o to related.R.ChannelsOverrideCommandsChannelsCMDOverrides.
// Uses the global database handle.
func (o *CommandsChannelsCMDOverride) SetChannelsOverrideG(insert bool, related *CommandsChannelsOverride) error {
	return o.SetChannelsOverride(boil.GetDB(), insert, related)
}

// SetChannelsOverrideP of the commands_channels_cmd_override to the related item.
// Sets o.R.ChannelsOverride to related.
// Adds o to related.R.ChannelsOverrideCommandsChannelsCMDOverrides.
// Panics on error.
func (o *CommandsChannelsCMDOverride) SetChannelsOverrideP(exec boil.Executor, insert bool, related *CommandsChannelsOverride) {
	if err := o.SetChannelsOverride(exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetChannelsOverrideGP of the commands_channels_cmd_override to the related item.
// Sets o.R.ChannelsOverride to related.
// Adds o to related.R.ChannelsOverrideCommandsChannelsCMDOverrides.
// Uses the global database handle and panics on error.
func (o *CommandsChannelsCMDOverride) SetChannelsOverrideGP(insert bool, related *CommandsChannelsOverride) {
	if err := o.SetChannelsOverride(boil.GetDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetChannelsOverride of the commands_channels_cmd_override to the related item.
// Sets o.R.ChannelsOverride to related.
// Adds o to related.R.ChannelsOverrideCommandsChannelsCMDOverrides.
func (o *CommandsChannelsCMDOverride) SetChannelsOverride(exec boil.Executor, insert bool, related *CommandsChannelsOverride) error {
	var err error
	if insert {
		if err = related.Insert(exec); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"commands_channels_cmd_overrides\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"channels_overrides_id"}),
		strmangle.WhereClause("\"", "\"", 2, commandsChannelsCMDOverridePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ChannelsOverridesID = related.ID

	if o.R == nil {
		o.R = &commandsChannelsCMDOverrideR{
			ChannelsOverride: related,
		}
	} else {
		o.R.ChannelsOverride = related
	}

	if related.R == nil {
		related.R = &commandsChannelsOverrideR{
			ChannelsOverrideCommandsChannelsCMDOverrides: CommandsChannelsCMDOverrideSlice{o},
		}
	} else {
		related.R.ChannelsOverrideCommandsChannelsCMDOverrides = append(related.R.ChannelsOverrideCommandsChannelsCMDOverrides, o)
	}

	return nil
}

// CommandsChannelsCMDOverridesG retrieves all records.
func CommandsChannelsCMDOverridesG(mods ...qm.QueryMod) commandsChannelsCMDOverrideQuery {
	return CommandsChannelsCMDOverrides(boil.GetDB(), mods...)
}

// CommandsChannelsCMDOverrides retrieves all the records using an executor.
func CommandsChannelsCMDOverrides(exec boil.Executor, mods ...qm.QueryMod) commandsChannelsCMDOverrideQuery {
	mods = append(mods, qm.From("\"commands_channels_cmd_overrides\""))
	return commandsChannelsCMDOverrideQuery{NewQuery(exec, mods...)}
}

// FindCommandsChannelsCMDOverrideG retrieves a single record by ID.
func FindCommandsChannelsCMDOverrideG(id int64, selectCols ...string) (*CommandsChannelsCMDOverride, error) {
	return FindCommandsChannelsCMDOverride(boil.GetDB(), id, selectCols...)
}

// FindCommandsChannelsCMDOverrideGP retrieves a single record by ID, and panics on error.
func FindCommandsChannelsCMDOverrideGP(id int64, selectCols ...string) *CommandsChannelsCMDOverride {
	retobj, err := FindCommandsChannelsCMDOverride(boil.GetDB(), id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindCommandsChannelsCMDOverride retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindCommandsChannelsCMDOverride(exec boil.Executor, id int64, selectCols ...string) (*CommandsChannelsCMDOverride, error) {
	commandsChannelsCMDOverrideObj := &CommandsChannelsCMDOverride{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"commands_channels_cmd_overrides\" where \"id\"=$1", sel,
	)

	q := queries.Raw(exec, query, id)

	err := q.Bind(commandsChannelsCMDOverrideObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from commands_channels_cmd_overrides")
	}

	return commandsChannelsCMDOverrideObj, nil
}

// FindCommandsChannelsCMDOverrideP retrieves a single record by ID with an executor, and panics on error.
func FindCommandsChannelsCMDOverrideP(exec boil.Executor, id int64, selectCols ...string) *CommandsChannelsCMDOverride {
	retobj, err := FindCommandsChannelsCMDOverride(exec, id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *CommandsChannelsCMDOverride) InsertG(whitelist ...string) error {
	return o.Insert(boil.GetDB(), whitelist...)
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *CommandsChannelsCMDOverride) InsertGP(whitelist ...string) {
	if err := o.Insert(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *CommandsChannelsCMDOverride) InsertP(exec boil.Executor, whitelist ...string) {
	if err := o.Insert(exec, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// Whitelist behavior: If a whitelist is provided, only those columns supplied are inserted
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns without a default value are included (i.e. name, age)
// - All columns with a default, but non-zero are included (i.e. health = 75)
func (o *CommandsChannelsCMDOverride) Insert(exec boil.Executor, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no commands_channels_cmd_overrides provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(commandsChannelsCMDOverrideColumnsWithDefault, o)

	key := makeCacheKey(whitelist, nzDefaults)
	commandsChannelsCMDOverrideInsertCacheMut.RLock()
	cache, cached := commandsChannelsCMDOverrideInsertCache[key]
	commandsChannelsCMDOverrideInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := strmangle.InsertColumnSet(
			commandsChannelsCMDOverrideColumns,
			commandsChannelsCMDOverrideColumnsWithDefault,
			commandsChannelsCMDOverrideColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		cache.valueMapping, err = queries.BindMapping(commandsChannelsCMDOverrideType, commandsChannelsCMDOverrideMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(commandsChannelsCMDOverrideType, commandsChannelsCMDOverrideMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"commands_channels_cmd_overrides\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.IndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"commands_channels_cmd_overrides\" DEFAULT VALUES"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		if len(wl) != 0 {
			cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into commands_channels_cmd_overrides")
	}

	if !cached {
		commandsChannelsCMDOverrideInsertCacheMut.Lock()
		commandsChannelsCMDOverrideInsertCache[key] = cache
		commandsChannelsCMDOverrideInsertCacheMut.Unlock()
	}

	return nil
}

// UpdateG a single CommandsChannelsCMDOverride record. See Update for
// whitelist behavior description.
func (o *CommandsChannelsCMDOverride) UpdateG(whitelist ...string) error {
	return o.Update(boil.GetDB(), whitelist...)
}

// UpdateGP a single CommandsChannelsCMDOverride record.
// UpdateGP takes a whitelist of column names that should be updated.
// Panics on error. See Update for whitelist behavior description.
func (o *CommandsChannelsCMDOverride) UpdateGP(whitelist ...string) {
	if err := o.Update(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateP uses an executor to update the CommandsChannelsCMDOverride, and panics on error.
// See Update for whitelist behavior description.
func (o *CommandsChannelsCMDOverride) UpdateP(exec boil.Executor, whitelist ...string) {
	err := o.Update(exec, whitelist...)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// Update uses an executor to update the CommandsChannelsCMDOverride.
// Whitelist behavior: If a whitelist is provided, only the columns given are updated.
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns are inferred to start with
// - All primary keys are subtracted from this set
// Update does not automatically update the record in case of default values. Use .Reload()
// to refresh the records.
func (o *CommandsChannelsCMDOverride) Update(exec boil.Executor, whitelist ...string) error {
	var err error
	key := makeCacheKey(whitelist, nil)
	commandsChannelsCMDOverrideUpdateCacheMut.RLock()
	cache, cached := commandsChannelsCMDOverrideUpdateCache[key]
	commandsChannelsCMDOverrideUpdateCacheMut.RUnlock()

	if !cached {
		wl := strmangle.UpdateColumnSet(
			commandsChannelsCMDOverrideColumns,
			commandsChannelsCMDOverridePrimaryKeyColumns,
			whitelist,
		)

		if len(whitelist) == 0 {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return errors.New("models: unable to update commands_channels_cmd_overrides, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"commands_channels_cmd_overrides\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, commandsChannelsCMDOverridePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(commandsChannelsCMDOverrideType, commandsChannelsCMDOverrideMapping, append(wl, commandsChannelsCMDOverridePrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err = exec.Exec(cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update commands_channels_cmd_overrides row")
	}

	if !cached {
		commandsChannelsCMDOverrideUpdateCacheMut.Lock()
		commandsChannelsCMDOverrideUpdateCache[key] = cache
		commandsChannelsCMDOverrideUpdateCacheMut.Unlock()
	}

	return nil
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q commandsChannelsCMDOverrideQuery) UpdateAllP(cols M) {
	if err := q.UpdateAll(cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values.
func (q commandsChannelsCMDOverrideQuery) UpdateAll(cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to update all for commands_channels_cmd_overrides")
	}

	return nil
}

// UpdateAllG updates all rows with the specified column values.
func (o CommandsChannelsCMDOverrideSlice) UpdateAllG(cols M) error {
	return o.UpdateAll(boil.GetDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o CommandsChannelsCMDOverrideSlice) UpdateAllGP(cols M) {
	if err := o.UpdateAll(boil.GetDB(), cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o CommandsChannelsCMDOverrideSlice) UpdateAllP(exec boil.Executor, cols M) {
	if err := o.UpdateAll(exec, cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o CommandsChannelsCMDOverrideSlice) UpdateAll(exec boil.Executor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), commandsChannelsCMDOverridePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"commands_channels_cmd_overrides\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, commandsChannelsCMDOverridePrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all in commandsChannelsCMDOverride slice")
	}

	return nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *CommandsChannelsCMDOverride) UpsertG(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	return o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *CommandsChannelsCMDOverride) UpsertGP(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *CommandsChannelsCMDOverride) UpsertP(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(exec, updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
func (o *CommandsChannelsCMDOverride) Upsert(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no commands_channels_cmd_overrides provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(commandsChannelsCMDOverrideColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs postgres problems
	buf := strmangle.GetBuffer()

	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range updateColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range whitelist {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	commandsChannelsCMDOverrideUpsertCacheMut.RLock()
	cache, cached := commandsChannelsCMDOverrideUpsertCache[key]
	commandsChannelsCMDOverrideUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := strmangle.InsertColumnSet(
			commandsChannelsCMDOverrideColumns,
			commandsChannelsCMDOverrideColumnsWithDefault,
			commandsChannelsCMDOverrideColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		update := strmangle.UpdateColumnSet(
			commandsChannelsCMDOverrideColumns,
			commandsChannelsCMDOverridePrimaryKeyColumns,
			updateColumns,
		)
		if len(update) == 0 {
			return errors.New("models: unable to upsert commands_channels_cmd_overrides, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(commandsChannelsCMDOverridePrimaryKeyColumns))
			copy(conflict, commandsChannelsCMDOverridePrimaryKeyColumns)
		}
		cache.query = queries.BuildUpsertQueryPostgres(dialect, "\"commands_channels_cmd_overrides\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(commandsChannelsCMDOverrideType, commandsChannelsCMDOverrideMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(commandsChannelsCMDOverrideType, commandsChannelsCMDOverrideMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert commands_channels_cmd_overrides")
	}

	if !cached {
		commandsChannelsCMDOverrideUpsertCacheMut.Lock()
		commandsChannelsCMDOverrideUpsertCache[key] = cache
		commandsChannelsCMDOverrideUpsertCacheMut.Unlock()
	}

	return nil
}

// DeleteP deletes a single CommandsChannelsCMDOverride record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *CommandsChannelsCMDOverride) DeleteP(exec boil.Executor) {
	if err := o.Delete(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteG deletes a single CommandsChannelsCMDOverride record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *CommandsChannelsCMDOverride) DeleteG() error {
	if o == nil {
		return errors.New("models: no CommandsChannelsCMDOverride provided for deletion")
	}

	return o.Delete(boil.GetDB())
}

// DeleteGP deletes a single CommandsChannelsCMDOverride record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *CommandsChannelsCMDOverride) DeleteGP() {
	if err := o.DeleteG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Delete deletes a single CommandsChannelsCMDOverride record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *CommandsChannelsCMDOverride) Delete(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no CommandsChannelsCMDOverride provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), commandsChannelsCMDOverridePrimaryKeyMapping)
	sql := "DELETE FROM \"commands_channels_cmd_overrides\" WHERE \"id\"=$1"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete from commands_channels_cmd_overrides")
	}

	return nil
}

// DeleteAllP deletes all rows, and panics on error.
func (q commandsChannelsCMDOverrideQuery) DeleteAllP() {
	if err := q.DeleteAll(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all matching rows.
func (q commandsChannelsCMDOverrideQuery) DeleteAll() error {
	if q.Query == nil {
		return errors.New("models: no commandsChannelsCMDOverrideQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from commands_channels_cmd_overrides")
	}

	return nil
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o CommandsChannelsCMDOverrideSlice) DeleteAllGP() {
	if err := o.DeleteAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAllG deletes all rows in the slice.
func (o CommandsChannelsCMDOverrideSlice) DeleteAllG() error {
	if o == nil {
		return errors.New("models: no CommandsChannelsCMDOverride slice provided for delete all")
	}
	return o.DeleteAll(boil.GetDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o CommandsChannelsCMDOverrideSlice) DeleteAllP(exec boil.Executor) {
	if err := o.DeleteAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o CommandsChannelsCMDOverrideSlice) DeleteAll(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no CommandsChannelsCMDOverride slice provided for delete all")
	}

	if len(o) == 0 {
		return nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), commandsChannelsCMDOverridePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"commands_channels_cmd_overrides\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, commandsChannelsCMDOverridePrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from commandsChannelsCMDOverride slice")
	}

	return nil
}

// ReloadGP refetches the object from the database and panics on error.
func (o *CommandsChannelsCMDOverride) ReloadGP() {
	if err := o.ReloadG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *CommandsChannelsCMDOverride) ReloadP(exec boil.Executor) {
	if err := o.Reload(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadG refetches the object from the database using the primary keys.
func (o *CommandsChannelsCMDOverride) ReloadG() error {
	if o == nil {
		return errors.New("models: no CommandsChannelsCMDOverride provided for reload")
	}

	return o.Reload(boil.GetDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *CommandsChannelsCMDOverride) Reload(exec boil.Executor) error {
	ret, err := FindCommandsChannelsCMDOverride(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *CommandsChannelsCMDOverrideSlice) ReloadAllGP() {
	if err := o.ReloadAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *CommandsChannelsCMDOverrideSlice) ReloadAllP(exec boil.Executor) {
	if err := o.ReloadAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *CommandsChannelsCMDOverrideSlice) ReloadAllG() error {
	if o == nil {
		return errors.New("models: empty CommandsChannelsCMDOverrideSlice provided for reload all")
	}

	return o.ReloadAll(boil.GetDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *CommandsChannelsCMDOverrideSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	commandsChannelsCMDOverrides := CommandsChannelsCMDOverrideSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), commandsChannelsCMDOverridePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"commands_channels_cmd_overrides\".* FROM \"commands_channels_cmd_overrides\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, commandsChannelsCMDOverridePrimaryKeyColumns, len(*o))

	q := queries.Raw(exec, sql, args...)

	err := q.Bind(&commandsChannelsCMDOverrides)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in CommandsChannelsCMDOverrideSlice")
	}

	*o = commandsChannelsCMDOverrides

	return nil
}

// CommandsChannelsCMDOverrideExists checks if the CommandsChannelsCMDOverride row exists.
func CommandsChannelsCMDOverrideExists(exec boil.Executor, id int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"commands_channels_cmd_overrides\" where \"id\"=$1 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, id)
	}

	row := exec.QueryRow(sql, id)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if commands_channels_cmd_overrides exists")
	}

	return exists, nil
}

// CommandsChannelsCMDOverrideExistsG checks if the CommandsChannelsCMDOverride row exists.
func CommandsChannelsCMDOverrideExistsG(id int64) (bool, error) {
	return CommandsChannelsCMDOverrideExists(boil.GetDB(), id)
}

// CommandsChannelsCMDOverrideExistsGP checks if the CommandsChannelsCMDOverride row exists. Panics on error.
func CommandsChannelsCMDOverrideExistsGP(id int64) bool {
	e, err := CommandsChannelsCMDOverrideExists(boil.GetDB(), id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// CommandsChannelsCMDOverrideExistsP checks if the CommandsChannelsCMDOverride row exists. Panics on error.
func CommandsChannelsCMDOverrideExistsP(exec boil.Executor, id int64) bool {
	e, err := CommandsChannelsCMDOverrideExists(exec, id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}
